//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Input/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""ShipMap"",
            ""id"": ""49de3092-1437-4a5e-881e-7ce3622a3903"",
            ""actions"": [
                {
                    ""name"": ""Forward"",
                    ""type"": ""Button"",
                    ""id"": ""01f7ab1a-8426-47b8-9ac4-f0b4283ad323"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""48d3488e-8f44-4c25-b7b7-0d3393509514"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""Button"",
                    ""id"": ""c2d229de-f0f9-4906-b6d5-440eac64db5c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d816fdc6-3a99-4aef-a5b9-82b27f51e45a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""817e004f-7b2d-48fd-9453-7fb9a01da500"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""bc00443d-8406-4a81-be0e-c674755ec3c9"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""7440bc20-e3f0-43b8-a6d6-0160f53779a7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""a4a5231b-936b-4137-93e0-e9edd8bffb0c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PC"",
            ""bindingGroup"": ""PC"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // ShipMap
        m_ShipMap = asset.FindActionMap("ShipMap", throwIfNotFound: true);
        m_ShipMap_Forward = m_ShipMap.FindAction("Forward", throwIfNotFound: true);
        m_ShipMap_Attack = m_ShipMap.FindAction("Attack", throwIfNotFound: true);
        m_ShipMap_Rotation = m_ShipMap.FindAction("Rotation", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ShipMap
    private readonly InputActionMap m_ShipMap;
    private IShipMapActions m_ShipMapActionsCallbackInterface;
    private readonly InputAction m_ShipMap_Forward;
    private readonly InputAction m_ShipMap_Attack;
    private readonly InputAction m_ShipMap_Rotation;
    public struct ShipMapActions
    {
        private @PlayerControls m_Wrapper;
        public ShipMapActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Forward => m_Wrapper.m_ShipMap_Forward;
        public InputAction @Attack => m_Wrapper.m_ShipMap_Attack;
        public InputAction @Rotation => m_Wrapper.m_ShipMap_Rotation;
        public InputActionMap Get() { return m_Wrapper.m_ShipMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ShipMapActions set) { return set.Get(); }
        public void SetCallbacks(IShipMapActions instance)
        {
            if (m_Wrapper.m_ShipMapActionsCallbackInterface != null)
            {
                @Forward.started -= m_Wrapper.m_ShipMapActionsCallbackInterface.OnForward;
                @Forward.performed -= m_Wrapper.m_ShipMapActionsCallbackInterface.OnForward;
                @Forward.canceled -= m_Wrapper.m_ShipMapActionsCallbackInterface.OnForward;
                @Attack.started -= m_Wrapper.m_ShipMapActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_ShipMapActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_ShipMapActionsCallbackInterface.OnAttack;
                @Rotation.started -= m_Wrapper.m_ShipMapActionsCallbackInterface.OnRotation;
                @Rotation.performed -= m_Wrapper.m_ShipMapActionsCallbackInterface.OnRotation;
                @Rotation.canceled -= m_Wrapper.m_ShipMapActionsCallbackInterface.OnRotation;
            }
            m_Wrapper.m_ShipMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Forward.started += instance.OnForward;
                @Forward.performed += instance.OnForward;
                @Forward.canceled += instance.OnForward;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @Rotation.started += instance.OnRotation;
                @Rotation.performed += instance.OnRotation;
                @Rotation.canceled += instance.OnRotation;
            }
        }
    }
    public ShipMapActions @ShipMap => new ShipMapActions(this);
    private int m_PCSchemeIndex = -1;
    public InputControlScheme PCScheme
    {
        get
        {
            if (m_PCSchemeIndex == -1) m_PCSchemeIndex = asset.FindControlSchemeIndex("PC");
            return asset.controlSchemes[m_PCSchemeIndex];
        }
    }
    public interface IShipMapActions
    {
        void OnForward(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnRotation(InputAction.CallbackContext context);
    }
}
